In [1]:
import pandas as pd
pd.set_option('display.max_rows', 5000)
pd.set_option('display.max_columns', 5000)
pd.options.display.max_colwidth = 1000

# Loading data

In [4]:
filepath = '../data/framingham/w2_dpuk_data_sharing_s1_s12_updated_20220203.xlsx'
df = pd.read_excel(filepath)

In [7]:
df.head()

,DATASET,CATEGORY,SUBCATEGORY,VARNUM,NAME,LABEL,DERIVED,TYPE,LENGTH,VALUES,FORMAT
0,Questionnaire,Basics,Demographics,2,ETHN_DS,"Ethnicity (1=white, 2=non-white)",1.0,1,8,NaN,NaN
1,Questionnaire,Basics,Demographics,3,SEX,Sex,NaN,1,4,1= MALE;2= FEMALE;,SEX
2,Questionnaire,Participation,Participation - general,4,PART,Participation status (S1),1.0,1,8,1= Participated;2= Died before participation;3= Non-response/withdrawal;,PARTICIP
3,Questionnaire,Participation,Participation - general,5,PARTTYP,"Participation type: Q, S, Q+S (S1)",1.0,1,8,1= Questionnaire only;2= Screening only;3= Questionnaire + screening;,PARTTYP
4,Questionnaire,Participation,Participation - general,6,QUESTYP,"Questionnaire type: main, tel (S1)",1.0,1,8,1= Main questionnaire;2= Telephone interview;3= Proxy interview;,QUEST

# Exploration

In [5]:
df.columns

Index(['DATASET', 'CATEGORY', 'SUBCATEGORY', 'VARNUM', 'NAME', 'LABEL',
       'DERIVED', 'TYPE', 'LENGTH', 'VALUES', 'FORMAT'],
      dtype='object')

In [11]:
df_v1 = df.drop(labels=["DERIVED","TYPE", "LENGTH", "FORMAT", "VARNUM"], axis="columns")

In [12]:
df_v1.columns

Index(['DATASET', 'CATEGORY', 'SUBCATEGORY', 'NAME', 'LABEL', 'VALUES'], dtype='object')

In [24]:
pd.unique(df_v1["SUBCATEGORY"]).tolist()

['Demographics',
 'Participation - general',
 'Participation - questionnaire',
 'Health',
 'Socioeconomic',
 'CVD',
 'Diabetes',
 'General health',
 'Longstanding illness',
 'Medication',
 'Stroke',
 "Women's health",
 'Diet',
 'Drinking',
 'Physical activity',
 'Smoking',
 'GHQ',
 'Life events',
 'Psychological states',
 'Satisfaction',
 'Traits',
 'Education',
 'Employment status/grade',
 'Social activities',
 'Social support',
 'Socio economic',
 'Work',
 'Participation',
 'Health questions',
 'Measurements',
 'Biomarkers',
 'Implementation',
 'Lipids',
 'Blood Pressure',
 'Blood Pressure: implementation',
 'Total']

In [21]:
df_v1[df_v1["SUBCATEGORY"]=="Demographics"].LABEL

0    Ethnicity (1=white, 2=non-white)
1                                 Sex
7              Q6 Marital status (S1)
8             Q7a First marriage (S1)
Name: LABEL, dtype: object

In [26]:
df_v1[df_v1["SUBCATEGORY"]=="Diabetes"] #No type

,DATASET,CATEGORY,SUBCATEGORY,NAME,LABEL,VALUES
69,Questionnaire,Health,Diabetes,DIABETES,Q27 Suffer from diabetes (S1),1= Yes;2= No;

In [27]:
df_v1[df_v1["SUBCATEGORY"]=="CVD"] #Questions

,DATASET,CATEGORY,SUBCATEGORY,NAME,LABEL,VALUES
36,Questionnaire,Health,CVD,BPCHKIE,Q24d Blood pressure check -insurance exam (S1),1= Yes;2= No;
37,Questionnaire,Health,CVD,BPCHKWK,Q24c Blood pressure check at work (S1),1= Yes;2= No;
38,Questionnaire,Health,CVD,BPCHKGP,Q24a Blood pressure check by gp (S1),1= Yes;2= No;
39,Questionnaire,Health,CVD,BPCHKDR,Q24b Blood pressure check by hospital doc (S1),1= Yes;2= No;
40,Questionnaire,Health,CVD,BPCHKOT,Q24e Blood pressure check by others (S1),1= Yes;2= No;
41,Questionnaire,Health,CVD,BPCHK,Q23 Has blood pressure ever been checked (S1),1= Yes;2= No;
42,Questionnaire,Health,CVD,CHPAIN,Q20a Any pain in the chest (S1),1= Yes;2= No;
43,Questionnaire,Health,CVD,CHPDOC,Q21b Discuss chest pain with doctor (S1),1= Yes;2= No;
44,Questionnaire,Health,CVD,CHPSTOP,Q20e Does chest pain go away (S1),1= Yes;2= No;
45,Questionnaire,Health,CVD,CHPLEV,Q20c Get chest pain when walking on flat (S1),1= Yes;2= No;
46,Questionnaire,Health,CVD,CHPUPH,Q20b Get chest pain when walking uphill (S1),1= Yes;2= No;
47,Questionnaire,Health,CVD,CHPEXT,Q21a Had severe pain across front of chest (S1),1= Yes;2= No;
48,Questionnaire,Health,CVD,CHPNUM,Q21d How many chest pain attacks (S1),NaN
49,Questionnaire,Health,CVD,CHPLOC,Q20g Location of chest pain (S1),1= CENTRAL CHEST;2= L. CHEST AND ARM;3= L. CHEST ONLY;4= OTHER;
50,Questionnaire,Health,CVD,CHPACT,Q20d Response to chest pain (S1),1= STOP;2= SLOW DOWN;3= CONTINUE;
51,Questionnaire,Health,CVD,CHPTIME,Q20f Time for chest pain to go away (S1),1= <=10 MIN.;2= > 10 MIN.;
52,Questionnaire,Health,CVD,HTRHOSP,Q22d Attended hospital for heart trouble (S1),1= Yes;2= No;
53,Questionnaire,Health,CVD,HTR,Q22a Any heart trouble ever suspected (S1),1= Yes;2= No;
54,Questionnaire,Health,CVD,HTRFST_A5,Q22b First year heart trouble suspected - age group (S1d),NaN
55,Questionnaire,Health,CVD,HTRDOC,Q22e Presently seeing doc for heart trouble (S1),1= Yes;2= No;
56,Questionnaire,Health,CVD,BPUPTRT,Q25c Ever treatment for high blood pressure (S1),1= Yes;2= No;
57,Questionnaire,Health,CVD,BPUP,Q25a Ever told blood pressure above normal (S1),1= Yes;2= No;
58,Questionnaire,Health,CVD,BPUPDRG,Q25e Treatment for high blood pressure now (S1),1= Yes;2= No;
59,Questionnaire,Health,CVD,BPUPFST_A5,Q25b Year first told blood pr. Above norm - age group (S1d),NaN
60,Questionnaire,Health,CVD,LPACT,Q26g Response to leg pain (S1),1= STOP;2= SLOW DOWN;3= CONTINUE;
61,Questionnaire,Health,CVD,LPTIME,Q26h Time for leg pain to go away when still (S1),1= Usually continues >10mins;2= Usually disapprs <=10mins;
62,Questionnaire,Health,CVD,LPSTILL,Q26b Leg pain begin when standing/sitting (S1),1= Yes;2= No;
63,Questionnaire,Health,CVD,LPSTOPGO,Q26f Leg pain disappear when walking (S1),1= Yes;2= No;
64,Questionnaire,Health,CVD,LPCALF,Q26c Get leg pain in calves (S1),1= Yes;2= No;
65,Questionnaire,Health,CVD,LPLEV,Q26e Get leg pain when walking on the flat (S1),1= Yes;2= No;
66,Questionnaire,Health,CVD,LPUPH,Q26d Get leg pain when walking uphill (S1),1= Yes;2= No;
67,Questionnaire,Health,CVD,LEGPAIN,Q26a Get leg pains whilst walking (S1),1= Yes;2= No;
68,Questionnaire,Health,CVD,MI,"Attended hosp for MI, asked at clinic (S1)",NaN

In [28]:
df_v1[df_v1["SUBCATEGORY"]=="Physical activity"]

,DATASET,CATEGORY,SUBCATEGORY,NAME,LABEL,VALUES
212,Questionnaire,Health behaviours,Physical activity,MILD,Q48a Freq of mild exercise (all Q versions) (S1),1= Often/3+ times a week;2= Sometimes/1-2 times a week;3= Seldom/1-3 times a month;4= Never/hardly ever;
213,Questionnaire,Health behaviours,Physical activity,MILD2,"Q48(v2,q35a) Frequency of mild exercise (S1)",1= OFTEN;2= SOMETIME;3= SELDOM;4= NEVER;
214,Questionnaire,Health behaviours,Physical activity,MILDHRS,Q48d Hours of mild exercise (corrected) (S1),NaN
215,Questionnaire,Health behaviours,Physical activity,MILD4,Q48(v4) Frequency of mild exercise (S1),1= 3+ times a week;2= 1-2 times a week;3= 1-3 times a month;4= Never/hardly ever;
216,Questionnaire,Health behaviours,Physical activity,MILD2HRS,Q48d Ave. Hours per week of mild exercise (S1),NaN
217,Questionnaire,Health behaviours,Physical activity,MOD2HRS,Q48e Ave. Hours per week of mod. Exercise (S1),NaN
218,Questionnaire,Health behaviours,Physical activity,MOD,Q48b Freq of mod exercise (all Q versions) (S1),1= Often/3+ times a week;2= Sometimes/1-2 times a week;3= Seldom/1-3 times a month;4= Never/hardly ever;
219,Questionnaire,Health behaviours,Physical activity,MOD2,"Q48(v2,q35a) Frequency of moderate exercise (S1)",1= OFTEN;2= SOMETIME;3= SELDOM;4= NEVER;
220,Questionnaire,Health behaviours,Physical activity,MOD4,Q48(v4) Frequency of mild exercise (S1),1= 3+ times a week;2= 1-2 times a week;3= 1-3 times a month;4= Never/hardly ever;
221,Questionnaire,Health behaviours,Physical activity,MODHRS,MODERATE EXERCISE – TOTAL HOURS/WEEK (S1),NaN
222,Questionnaire,Health behaviours,Physical activity,VIG2HRS,Q48f Ave. Hours per week of vig. Exercise (S1),NaN
223,Questionnaire,Health behaviours,Physical activity,VIG,Q48c Freq of vig exercise (all Q versions) (S1),1= Often/3+ times a week;2= Sometimes/1-2 times a week;3= Seldom/1-3 times a month;4= Never/hardly ever;
224,Questionnaire,Health behaviours,Physical activity,VIG2,"Q48(v2,q35a) Frequency of vigorous exercise (S1)",1= OFTEN;2= SOMETIME;3= SELDOM;4= NEVER;
225,Questionnaire,Health behaviours,Physical activity,VIG4,Q48(v4) Frequency of mild exercise (S1),1= 3+ times a week;2= 1-2 times a week;3= 1-3 times a month;4= Never/hardly ever;
226,Questionnaire,Health behaviours,Physical activity,VIGHRS,Vigorous exercise – Total hours/week (s1),NaN

In [29]:
df_v1[df_v1["SUBCATEGORY"]=="Measurements"] #Questions

,DATASET,CATEGORY,SUBCATEGORY,NAME,LABEL,VALUES
661,Screening,Anthropometry,Measurements,BMI,Body mass index (S1),NaN
662,Screening,Anthropometry,Measurements,HEIGHT,Height cms (S1),NaN
663,Screening,Anthropometry,Measurements,WEIGHT,Weight in kgs (S1),NaN

In [31]:
df_v1[df_v1["SUBCATEGORY"]=="Smoking"]

,DATASET,CATEGORY,SUBCATEGORY,NAME,LABEL,VALUES
227,Questionnaire,Health behaviours,Smoking,SMKSTART_C,Q41 Age when started smoking - top coded (S1d),NaN
228,Questionnaire,Health behaviours,Smoking,SMKSTOP_C,Q40d Age when stopped smoking - top coded (S1d),NaN
229,Questionnaire,Health behaviours,Smoking,SMOKE,Q39a Currently smoke cigarettes (S1),1= Yes;2= No;
230,Questionnaire,Health behaviours,Smoking,SMKPAST,Q40a Ever smoked cigarettes (S1),1= Yes;2= No;
231,Questionnaire,Health behaviours,Smoking,CIGNOPST_C,Q40b No.manufd cigs smoked/day in past - top coded (S1d),NaN
232,Questionnaire,Health behaviours,Smoking,CIGNUM_C,Q39c No.manufd. cigs smoke/day - top coded (S1d),NaN
233,Questionnaire,Health behaviours,Smoking,TOBOZPST_C,Q40c Ounces -tobacco used per week in past - top coded (S1d),NaN
234,Questionnaire,Health behaviours,Smoking,TOBOZ,Q39d Ounces of tobacco smoked per week (S1),NaN
235,Questionnaire,Health behaviours,Smoking,CIGFILT,Q39b Smoke manufactured filters now (S1),1= Yes;2= No;
236,Questionnaire,Health behaviours,Smoking,CIGTYPE,Q39b Type of cigarettes smoked (1-3) (S1),1= FILTER;2= UNFILTER;3= HAND ROLLED;
237,Questionnaire,Health behaviours,Smoking,CIGARNUM_C,Q42b No.cigars/week smoked now - top coded (S1d),NaN
238,Questionnaire,Health behaviours,Smoking,PIPENUM,Q42c No. Of pipes smoked per week (S1),NaN
239,Questionnaire,Health behaviours,Smoking,PIPEOZ_C,Q42d Tob. Ounces for pipe per week used now - top coded (S1d),NaN
240,Questionnaire,Health behaviours,Smoking,PIPE,Q42c Smoke a pipe now (S1),1= Yes;2= No;
241,Questionnaire,Health behaviours,Smoking,CIGARS,Q42a Smoke cigars now (S1),1= Yes;2= No;

In [33]:
df_v1[df_v1["SUBCATEGORY"]=="Drinking"]

,DATASET,CATEGORY,SUBCATEGORY,NAME,LABEL,VALUES
194,Questionnaire,Health behaviours,Drinking,ALCWK,Q44a Alcoholic drink in past week (S1),1= Yes;2= No;
195,Questionnaire,Health behaviours,Drinking,ALCWK0,Q44a Alc drink in past wk (edited) (S1d),NaN
196,Questionnaire,Health behaviours,Drinking,BEERMAX0,Q45d Max beer pints in 1 sitting (edited) (S1),NaN
197,Questionnaire,Health behaviours,Drinking,BEERWK0,Q44d Pints of beer in past week (edited) (S1),NaN
198,Questionnaire,Health behaviours,Drinking,BEERUWK0,Units of beer in past week (edited) (S1d),NaN
199,Questionnaire,Health behaviours,Drinking,BEERNRM0,Q45b Usual beer pints in 1 sitting (edited) (S1),NaN
200,Questionnaire,Health behaviours,Drinking,ALCCH5YR,Q43b Changed drinking habits in last 5 years (S1),1= Yes;2= No;
201,Questionnaire,Health behaviours,Drinking,ALCCH,Q43c Drink more or less in the past (S1),1= LOT MORE;2= BIT MORE;3= BIT LESS;4= LOT LESS;
202,Questionnaire,Health behaviours,Drinking,ALCMXSOC,Q45e Drink most during social occasions (S1),1= Yes;2= No;
203,Questionnaire,Health behaviours,Drinking,ALCMXOTH,Q45e Drink most for other reasons (S1),1= Yes;2= No;
204,Questionnaire,Health behaviours,Drinking,ALCMXBRD,Q45e Drink most when bored (S1),1= Yes;2= No;
205,Questionnaire,Health behaviours,Drinking,ALCMXPRS,Q45e Drink most when under pressure (S1),1= Yes;2= No;
206,Questionnaire,Health behaviours,Drinking,ALCMXUPS,Q45e Drink most when upset (S1),1= Yes;2= No;
207,Questionnaire,Health behaviours,Drinking,ALCRED,Q43d Reason for reduced drinking (S1),1= DOCTOR;2= HEALTH;3= FINANCE;4= OTHER;
208,Questionnaire,Health behaviours,Drinking,SPRTWK0,Q44b Meas. Of spirits in past week (edited) (S1),NaN
209,Questionnaire,Health behaviours,Drinking,SPWINRM0,Q45a Usual sprts/wine in 1 sitting (edited) (S1),NaN
210,Questionnaire,Health behaviours,Drinking,SPWIMAX0,Q45c Max sprts/wine in 1 sitting (edited) (S1),NaN
211,Questionnaire,Health behaviours,Drinking,WINEWK0,Q44c Glasses of wine in past week (edited) (S1),NaN

In [36]:
df_v1[df_v1["SUBCATEGORY"]=="Women's health"]

,DATASET,CATEGORY,SUBCATEGORY,NAME,LABEL,VALUES
242,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ01,Q80 Recently been able to concentrate (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
243,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ02,Q81 Recently lost much sleep (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
244,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ03,Q82 Recently been having restless nights (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
245,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ04,Q83 Recently been managing to busy (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
246,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ05,Q84 Recently getting outside as usual (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
247,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ06,Q85 Recently coping as well as others (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
248,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ07,Q86 Recently felt doing things well (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
249,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ08,Q87 Recently happy how a task was done (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
250,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ09,Q88 Recently felt warmth to those close (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
251,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ10,Q89 Recently felt easy to mix with others (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
252,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ11,Q90 Recently spent time chatting to others (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
253,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ12,Q91 Recently felt playing a useful role (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
254,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ13,Q92 Recently felt able to make decisions (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
255,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ14,Q93 Recently felt constantly under strain (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
256,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ15,Q94 Recently felt unable to fix problems (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
257,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ16,Q95 Recently found life a struggle (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
258,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ17,Q96 Recently enjoyed normal activities (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
259,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ18,Q97 Recently been taking things hard (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
260,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ19,Q98 Recently been getting scared (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
261,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ20,Q99 Recently been able to face problems (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
262,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ21,Q100 Recently found things overwhelming (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
263,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ22,Q101 Recently been feeling unhappy (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
264,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ23,Q102 Recently been losing confidence (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
265,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ24,Q103 Recently thought yourself worthless (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
266,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ25,Q104 Recently felt life is hopeless (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
267,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ26,Q105 Recently felt hopeful re the future (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
268,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ27,Q106 Recently been reasonably happy (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
269,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ28,Q107 Recently been feeling nervous (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
270,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ29,Q108 Recently felt life not worth living (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;
271,Questionnaire,"Personality, Mental Health & Well Being",GHQ,GHQ30,Q109 Recently felt nerves stopped you (S1),1= BETTER;2= USUAL;3= <USUAL;4= WORSE;

In [38]:
df_v1[df_v1["SUBCATEGORY"]=="Diet"]

,DATASET,CATEGORY,SUBCATEGORY,NAME,LABEL,VALUES
170,Questionnaire,Health behaviours,Diet,BREADNO,Q47b No. Of bread slices usually eat (S1),1= NONE;2= 1-2;3= 3-6;4= 7-12;5= >13;
171,Questionnaire,Health behaviours,Diet,BREAD,Q47a Type of bread usually eat (S1),1= White;2= Wholemeal;3= Granary;4= Other brown;5= Combo= white+brown;6= Do not eat bread;
172,Questionnaire,Health behaviours,Diet,CEREAL,Q47m Frequency of eating brekkie cereal (S1),1= SELDOM;2= <1/MONTH;3= 1-3/MNTH;4= 1-2/WEEK;5= 3-4/WEEK;6= 5-6/WEEK;7= >=7/WEEK;
173,Questionnaire,Health behaviours,Diet,CEREALHF,Q47n Freq. Of eating hi fibre cereals (S1),1= < 1/WEEK;2= 1-2/WEEK;3= 3-4/WEEK;4= 5-6/WEEK;5= > 7/WEEK;
174,Questionnaire,Health behaviours,Diet,CEREALTY,Q7n Type of cereal usually eat (S1),1= ALLBRAN;2= MUESLI;3= WEETABIX;4= BRANFLKS;5= PUFF WHT;6= OTHER;7= COMBO;
175,Questionnaire,Health behaviours,Diet,CER4,Q47n Usually eat branflakes (S1),1= Yes;2= No;
176,Questionnaire,Health behaviours,Diet,CER3,Q47n Usually eat weetabix (S1),1= Yes;2= No;
177,Questionnaire,Health behaviours,Diet,CER1,Q47n Usually eat all bran (S1),1= Yes;2= No;
178,Questionnaire,Health behaviours,Diet,CER6,Q47n Usually eat all hi fibre cereal (S1),1= Yes;2= No;
179,Questionnaire,Health behaviours,Diet,CER5,Q47n Usually eat all puffed wheat (S1),1= Yes;2= No;
180,Questionnaire,Health behaviours,Diet,CER2,Q47n Usually eat muesli (S1),1= Yes;2= No;
181,Questionnaire,Health behaviours,Diet,CHEESE,Q47h Frequency of using cheese (S1),1= SELDOM;2= <1/MONTH;3= 1-3/MNTH;4= 1-2/WEEK;5= 3-4/WEEK;6= 5-6/WEEK;7= >=7/WEEK;
182,Questionnaire,Health behaviours,Diet,COFFAV,Q46b Average no. Of cups of coffee per day (S1),NaN
183,Questionnaire,Health behaviours,Diet,COFFTYPE,Q46c Type of coffee usually drink (S1),1= INSTANT;2= FILTERED;3= PERCOLTD;4= DECAF;5= OTHER;
184,Questionnaire,Health behaviours,Diet,CREAM,Q47g Frequency of using cream (S1),1= SELDOM;2= <1/MONTH;3= 1-3/MNTH;4= 1-2/WEEK;5= 3-4/WEEK;6= 5-6/WEEK;7= >=7/WEEK;
185,Questionnaire,Health behaviours,Diet,EGGSV2,Q47(v2) No. Eggs eaten per week (S1),1= NONE;2= 1-2;3= 3-4;4= 5 OR MORE;
186,Questionnaire,Health behaviours,Diet,EGGSV4,Q47l Frequency of eating eggs (S1),1= SELDOM;2= <1/MONTH;3= 1-3/MNTH;4= 1-2/WEEK;5= 3-4/WEEK;6= 5-6/WEEK;7= >=7/WEEK;
187,Questionnaire,Health behaviours,Diet,FRUITVEG,Q47j Frequency of eating fruit or vegies (S1),1= SELDOM;2= <1/MONTH;3= 1-3/MNTH;4= 1-2/WEEK;5= 3-4/WEEK;6= 5-6/WEEK;7= DAILY;8= 2+/DAY;8= 4+/DAY;
188,Questionnaire,Health behaviours,Diet,MEAT,Q47k Frequency of meals containing meat (S1),1= SELDOM;2= <1/MONTH;3= 1-3/MNTH;4= 1-2/WEEK;5= 3-4/WEEK;6= 5-6/WEEK;7= >=7/WEEK;
189,Questionnaire,Health behaviours,Diet,MILKAMT,Q47f Amount of milk drunk per day (S1),1= NONE;2= <HALF;3= >HALF;4= 1-2;5= >2;
190,Questionnaire,Health behaviours,Diet,MILK,Q47e Type of milk usually drink (S1),1= NONE;2= GOLD TOP;3= WHOLE MLK;4= SKIMMED;5= SEMI-SKD;6= OTHER;7= COMB;
191,Questionnaire,Health behaviours,Diet,SPREADSZ,Q47d Average size of spread used per slice (S1),1= 1;2= 2;3= 3;4= 4;
192,Questionnaire,Health behaviours,Diet,SPREAD,Q47c Type of butter/margarine usually use (S1),1= BUTTER;2= HARD MRG;3= SOFT MRG;4= POLYUNS;5= LOW CAL.;6= RARE USE;7= COMBO;
193,Questionnaire,Health behaviours,Diet,TEAAV,Q46a Average no. Of cups of tea per day (S1),NaN